# neptune
neptune_project: LBM-Eraser
timestep_sampling: custom_timesteps
unet_input_channels: 4
vae_num_channels: 4
selected_timesteps: [250, 500, 750, 1000]
prob: [0.25, 0.25, 0.25, 0.25]
pixel_loss_type: lpips # l1 l2
pixel_loss_weight: 10.0
latent_loss_type: l2 # l1 l2
latent_loss_weight: 1.0
bridge_noise_sigma: 0.05 # see Appendix A.1
conditioning_images_keys: []
conditioning_masks_keys: []
image_size: [536, 960] # (H, W), while original RORD dimension is [H=540, W=960]
resize_mode: CenterCrop # CenterCrop or Resize

train_shards: 
- "data/RORD-processed/train-{000000..000412}.tar"
validation_shards: 
- "data/RORD-processed/val-lite-{000000..000007}.tar" # 8 shards, one per GPU

batch_size: 4
learning_rate: 3e-5 # see Appendix A.1
optimizer: AdamW
num_steps: [1, 4]
log_interval: 10 # log the loss/lr every 10 steps
max_epochs: 50
gradient_clip_val: null

# Validation
limit_val_batches: 2 # 2 x 4 (batch_size) x 8 GPUs = 64 samples for validation
val_check_interval: 500 # 500 means every 4 (batch) * 8 (gpus) * 500 = 16000 training samples

# Checkpointing
resume_from_checkpoint: false
save_interval: 500 # synced with val_check_interval
# Each checkpoint is 5.1GB, 25 checkpoints = 125GB
# 25 * 500 = 12500 last steps are covered
save_top_k: 25
save_ckpt_path: ./checkpoints

